name: Deploy Backend to Hugging Face

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Only trigger when the backend folder changes

jobs:
  deploy-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to push a subtree

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Add Hugging Face remote using the securely injected token
          git remote add hf https://aryanracha:$HF_TOKEN@huggingface.co/spaces/aryanracha/meghdrishtii
          
          # Force split and push the backend folder to the root of the HF main branch
          git subtree split --prefix backend -b deploy-backend
          git push hf deploy-backend:main --force
